# Generated by Django 5.2.16 on 2026-07-29 07:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expense_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    def copy_participants(apps, schema_editor):
        Expense = apps.get_model('core', 'Expense')
        ExpenseParticipant = apps.get_model('core', 'ExpenseParticipant')
        for expense in Expense.objects.all().iterator():
            rows = [
                ExpenseParticipant(expense_id=expense.pk, user_id=user_id, role=role)
                for role, user_ids in (('paid', expense.paid_by or []),
                                       ('split', expense.split_on or []))
                for user_id in user_ids
            ]
            ExpenseParticipant.objects.bulk_create(rows, ignore_conflicts=True)

    operations = [
        migrations.CreateModel(
            name='ExpenseParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('paid', 'Paid by'), ('split', 'Split with')], max_length=5)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='core.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('expense', 'user', 'role'), name='unique_expense_participant_role')],
            },
        ),
        migrations.RunPython(copy_participants, migrations.RunPython.noop),
        migrations.RemoveField(model_name='expense', name='paid_by'),
        migrations.RemoveField(model_name='expense', name='split_on'),
    ]
