# Generated by Django 5.2.16 on 2026-07-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseparticipant',
            name='share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expenseparticipant',
            name='share_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
