# Generated by Django 5.2.6 on 2026-10-08 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_optional_descriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
