# Generated by Django 5.2.6 on 2026-10-08 13:00

import core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_activity_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=core.images.RandomName('groups')),
        ),
    ]
