# Generated by Django 5.2.6 on 2026-10-08 12:28

from django.db import migrations, models


def verify_existing_users(apps, schema_editor):
    """Accounts that predate verification keep working."""
    apps.get_model('user', 'User').objects.update(email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(verify_existing_users, migrations.RunPython.noop),
    ]
