# Generated by Django 5.2.6 on 2026-10-08 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_activity_group'),
        ('user', '0003_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinvite',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='groupinvite',
            name='token',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='groupinvite',
            name='invitee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_invites', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='groupinvite',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), models.Q(('email', ''), _negated=True)), fields=('group', 'email'), name='unique_pending_group_email_invite'),
        ),
    ]
