# Generated by Django 5.2.6 on 2026-10-08 13:00

import core.images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_email_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=core.images.RandomName('avatars')),
        ),
    ]
