-keepattributes *Annotation*, InnerClasses, Signature
-keepclassmembers class com.splitwise.app.data.** { *** Companion; }
-keepclasseswithmembers class com.splitwise.app.data.** { kotlinx.serialization.KSerializer serializer(...); }
